apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: opifex-alertmanager
  labels:
    app.kubernetes.io/name: opifex-alertmanager
    app.kubernetes.io/part-of: opifex-monitoring
    app.kubernetes.io/version: "v0.25.0"

namespace: opifex-monitoring

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: opifex-alertmanager
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: opifex-framework

configMapGenerator:
  - name: alertmanager-config
    files:
      - alertmanager.yml

images:
  - name: prometheus/alertmanager
    newTag: v0.25.0
