apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: opifex-grafana
  labels:
    app.kubernetes.io/name: opifex-grafana
    app.kubernetes.io/part-of: opifex-monitoring
    app.kubernetes.io/version: "v10.0.0"

namespace: opifex-monitoring

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - service-external.yaml
  - serviceaccount.yaml
  - dashboards-configmap.yaml
  - datasources-configmap.yaml

commonLabels:
  app.kubernetes.io/name: opifex-grafana
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: opifex-framework

configMapGenerator:
  - name: grafana-config
    files:
      - grafana.ini

images:
  - name: grafana/grafana
    newTag: "10.0.0"
